### ISSUE TITLE
below Tibetan syllables can't be converted.

### ISSUE THREAD

**Issue by riggy2013** [eroux/pyewts#5]
I used pyewts to convert some text and here are the Tibetan syllables with errors.

dangs
zhwa
dwang
rma
tshe
phywa
dge
rgya
dwags

I don't have much time to look into it by myself. Will someone pls fix them?

Interestingly, it can convert left parenthesis but not the right one. For example, 

(rtse mgron)

will be converted to 

༼རྩེ་མགྲོན)

**Comment by eroux** [comment]
thanks! I'll be traveling in the next 10 days so I probably won't have time soon, but I'll look into this yes

**Comment by eroux** [comment]
I've fixed an exception and the right parentheses. There's definitely a bug with the wasur, but for 

```
dangs
rma
tshe
dge
rgya
```

I'm getting

```
དངས
རྨ
ཚེ
དགེ
རྒྱ
```

which look ok to me... what result do you get?

**Comment by eroux** [comment]
I've just fixed the wasur issue

**Comment by riggy2013** [comment]
they are good now. great job!

**Comment by eroux** [comment]
I'm pretty sure this can be closed, please reopen if it isn't
